#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
trigger:
  branch:
    exclude:
    - gh-pages

#---------------------------------#		
#       build configuration       #		
#---------------------------------#
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: mcr.microsoft.com/dotnet/runtime:5.0-alpine3.14-arm32v7
  commands:
  - chmod +x build.sh
  - bash ./build.sh
