#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
trigger:
  branch:
    exclude:
    - gh-pages

#---------------------------------#		
#       build configuration       #		
#---------------------------------#
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: mcr.microsoft.com/dotnet/runtime:6.0-bullseye-slim-arm32v7
  commands:
  - apt update
  - apt upgrade
  - apt install curl
  - chmod +x build.sh
  - bash ./build.sh
