#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
trigger:
  branch:
    exclude:
    - gh-pages

#---------------------------------#		
#       build configuration       #		
#---------------------------------#
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: mcr.microsoft.com/dotnet/runtime:6.0-alpine3.15-arm32v7
  commands:
  - apt-get update
  - apt-get --yes install sudo
  - chmod +x build.sh
  - bash /build.sh
