trigger:
  branches:
    include:
    - master
    exclude:
    - gh-pages

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

jobs:
- template: build/azure-pipelines.job.template.yml
  parameters:
    name: Windows
    vmImage: 'windows-2019'
    scriptFileName: .\build.ps1