using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Engines;
using BenchmarkDotNet.Extensions;
using BenchmarkDotNet.Helpers.Reflection.Emit;
using Perfolizer.Horology;
using System;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using static BenchmarkDotNet.Toolchains.InProcess.Emit.Implementation.RunnableConstants;

namespace BenchmarkDotNet.Toolchains.InProcess.Emit.Implementation;

partial class RunnableEmitter
{
    // TODO: update this to support runtime-async.
    private sealed class AsyncCoreEmitter : RunnableEmitter
    {
        private FieldInfo workloadContinuerAndValueTaskSourceField;
        private FieldInfo clockField;
        private FieldInfo invokeCountField;

        protected override void EmitExtraFields(TypeBuilder fieldsContainerBuilder)
        {
            base.EmitExtraFields(fieldsContainerBuilder);

            workloadContinuerAndValueTaskSourceField = fieldsContainerBuilder.DefineField(
                WorkloadContinuerAndValueTaskSourceFieldName,
                typeof(WorkloadContinuerAndValueTaskSource),
                FieldAttributes.Public);
            clockField = fieldsContainerBuilder.DefineField(
                ClockFieldName,
                typeof(IClock),
                FieldAttributes.Public);
            invokeCountField = fieldsContainerBuilder.DefineField(
                InvokeCountFieldName,
                typeof(long),
                FieldAttributes.Public);
        }

        protected override void EmitExtraGlobalCleanup(ILGenerator ilBuilder, LocalBuilder? thisLocal)
        {
            // __fieldsContainer.workloadContinuerAndValueTaskSource?.Complete();

            var callCompleteLabel = ilBuilder.DefineLabel(); // IL_0022
            var skipCompleteLabel = ilBuilder.DefineLabel(); // IL_0027

            /*
                // WorkloadContinuerAndValueTaskSource workloadContinuerAndValueTaskSource = runnable_.__fieldsContainer.workloadContinuerAndValueTaskSource;
                IL_0011: ldloc.1
                IL_0012: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_0/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_0::__fieldsContainer
                IL_0017: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_0/FieldsContainer::workloadContinuerAndValueTaskSource
             */
            if (thisLocal != null)
            {
                ilBuilder.EmitLdloc(thisLocal);
            }
            else
            {
                ilBuilder.Emit(OpCodes.Ldarg_0);
            }
            ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
            ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
            /*
                // if (workloadContinuerAndValueTaskSource != null)
                IL_001c: dup
                IL_001d: brtrue.s IL_0022
             */
            ilBuilder.Emit(OpCodes.Dup);
            ilBuilder.Emit(OpCodes.Brtrue_S, callCompleteLabel);

            /*
                IL_001f: pop
                IL_0020: br.s IL_0027
             */
            ilBuilder.Emit(OpCodes.Pop);
            ilBuilder.Emit(OpCodes.Br, skipCompleteLabel);

            /*
                // workloadContinuerAndValueTaskSource.Complete();
                IL_0022: call instance void [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::Complete()
             */
            ilBuilder.MarkLabel(callCompleteLabel);
            ilBuilder.Emit(OpCodes.Call, typeof(WorkloadContinuerAndValueTaskSource).GetMethod(nameof(WorkloadContinuerAndValueTaskSource.Complete), BindingFlags.Public | BindingFlags.Instance));

            ilBuilder.MarkLabel(skipCompleteLabel);
        }

        protected override void EmitCoreImpl()
        {
            EmitOverhead();
            EmitWorkload();
        }

        private void EmitOverhead()
        {
            var noUnrollMethod = EmitNoUnrollMethod();
            EmitUnrollMethod();

            MethodInfo EmitNoUnrollMethod()
            {
                /*
                    // private ValueTask<ClockSpan> OverheadActionNoUnroll(long invokeCount, IClock clock)
                    .method private hidebysig 
	                    instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> OverheadActionNoUnroll (
		                    int64 invokeCount,
		                    class [Perfolizer]Perfolizer.Horology.IClock clock
	                    ) cil managed flags(0200)
                 */
                var invokeCountArg = new EmitParameterInfo(0, InvokeCountParamName, typeof(long));
                var methodBuilder = runnableBuilder
                    .DefineNonVirtualInstanceMethod(
                        OverheadActionNoUnrollMethodName,
                        MethodAttributes.Private,
                        EmitParameterInfo.CreateReturnParameter(typeof(ValueTask<ClockSpan>)),
                        [
                            invokeCountArg,
                            new EmitParameterInfo(1, ClockParamName, typeof(IClock))
                        ]
                    )
                    .SetAggressiveOptimizationImplementationFlag();
                invokeCountArg.SetMember(methodBuilder);

                var ilBuilder = methodBuilder.GetILGenerator();

                /*
                    .locals init (
		                [0] valuetype [Perfolizer]Perfolizer.Horology.StartedClock startedClock
	                )
                 */
                var startedClockLocal = ilBuilder.DeclareLocal(typeof(StartedClock));

                var startLoopLabel = ilBuilder.DefineLabel(); // IL_000f

                /*
                    // StartedClock startedClock = ClockExtensions.Start(clock);
	                IL_0000: ldarg.2
	                IL_0001: call valuetype [Perfolizer]Perfolizer.Horology.StartedClock [Perfolizer]Perfolizer.Horology.ClockExtensions::Start(class [Perfolizer]Perfolizer.Horology.IClock)
	                IL_0006: stloc.0
                 */
                ilBuilder.Emit(OpCodes.Ldarg_2);
                ilBuilder.Emit(OpCodes.Call, GetStartClockMethod());
                ilBuilder.EmitStloc(startedClockLocal);

                // loop
                ilBuilder.EmitLoopBeginFromArgToZero(out var loopStartLabel, out var loopHeadLabel);
                {
                    /*
	                    // __Overhead();
		                IL_0009: ldarg.0
		                IL_000a: call instance void BenchmarkDotNet.Autogenerated.Runnable_1::__Overhead()
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    EmitLoadArgFieldsForCall(ilBuilder, null);
                    ilBuilder.Emit(OpCodes.Call, overheadImplementationMethod);
                }
                ilBuilder.EmitLoopEndFromArgToZero(loopStartLabel, loopHeadLabel, invokeCountArg);

                /*
	                // return new ValueTask<ClockSpan>(startedClock.GetElapsed());
	                IL_001a: ldloca.s 0
	                IL_001c: call instance valuetype [Perfolizer]Perfolizer.Horology.ClockSpan [Perfolizer]Perfolizer.Horology.StartedClock::GetElapsed()
	                IL_0021: newobj instance void valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan>::.ctor(!0)
	                IL_0026: ret
                 */
                ilBuilder.EmitLdloca(startedClockLocal);
                ilBuilder.Emit(OpCodes.Call, typeof(StartedClock).GetMethod(nameof(StartedClock.GetElapsed), BindingFlags.Public | BindingFlags.Instance));
                ilBuilder.Emit(OpCodes.Newobj, typeof(ValueTask<ClockSpan>).GetConstructor([typeof(ClockSpan)]));
                ilBuilder.Emit(OpCodes.Ret);

                return methodBuilder;
            }

            void EmitUnrollMethod()
            {
                /*
                    // private ValueTask<ClockSpan> OverheadActionUnroll(long invokeCount, IClock clock)
                    .method private hidebysig 
	                    instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> OverheadActionUnroll (
		                    int64 invokeCount,
		                    class [Perfolizer]Perfolizer.Horology.IClock clock
	                    ) cil managed flags(0200)
                 */
                var methodBuilder = runnableBuilder
                    .DefineNonVirtualInstanceMethod(
                        OverheadActionUnrollMethodName,
                        MethodAttributes.Private,
                        EmitParameterInfo.CreateReturnParameter(typeof(ValueTask<ClockSpan>)),
                        [
                            new EmitParameterInfo(0, InvokeCountParamName, typeof(long)),
                            new EmitParameterInfo(1, ClockParamName, typeof(IClock))
                        ]
                    )
                    .SetAggressiveOptimizationImplementationFlag();

                var ilBuilder = methodBuilder.GetILGenerator();

                /*
                    // return OverheadActionNoUnroll(invokeCount * 16, clock);
	                IL_0000: ldarg.0
	                IL_0001: ldarg.1
	                IL_0002: ldc.i4.s 16
	                IL_0004: conv.i8
	                IL_0005: mul
	                IL_0006: ldarg.2
	                IL_0007: call instance valuetype [System.Threading.Tasks.Extensions]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> BenchmarkDotNet.Autogenerated.Runnable_0::OverheadActionNoUnroll(int64, class [Perfolizer]Perfolizer.Horology.IClock)
	                IL_000c: ret
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldarg_1);
                ilBuilder.EmitLdc_I4(jobUnrollFactor);
                ilBuilder.Emit(OpCodes.Conv_I8);
                ilBuilder.Emit(OpCodes.Mul);
                ilBuilder.Emit(OpCodes.Ldarg_2);
                ilBuilder.Emit(OpCodes.Call, noUnrollMethod);
                ilBuilder.Emit(OpCodes.Ret);
            }
        }

        private Type GetWorkloadCoreAsyncMethodBuilderType()
        {
            // If the benchmark method overrode the caller type, use that type to get the builder type.
            if (Descriptor.WorkloadMethod.ResolveAttribute<AsyncCallerTypeAttribute>() is AsyncCallerTypeAttribute asyncCallerTypeAttribute)
            {
                return GetBuilderTypeFromUserSpecifiedAsyncType(asyncCallerTypeAttribute.AsyncCallerType);
            }
            // If the benchmark method overrode the builder, use the same builder.
            if (Descriptor.WorkloadMethod.GetAsyncMethodBuilderAttribute() is { } methodAttr
                && methodAttr.GetType().GetProperty(nameof(AsyncMethodBuilderAttribute.BuilderType), BindingFlags.Public | BindingFlags.Instance)?.GetValue(methodAttr) is Type methodBuilderType)
            {
                return methodBuilderType;
            }
            if (Descriptor.WorkloadMethod.ReturnType.GetAsyncMethodBuilderAttribute() is { } typeAttr
                && typeAttr.GetType().GetProperty(nameof(AsyncMethodBuilderAttribute.BuilderType), BindingFlags.Public | BindingFlags.Instance)?.GetValue(typeAttr) is Type typeBuilderType)
            {
                return GetConcreteBuilderType(typeBuilderType);
            }
            // Task and Task<T> are not annotated with their builder type, the C# compiler special-cases them.
            if (Descriptor.WorkloadMethod.ReturnType.IsGenericType && Descriptor.WorkloadMethod.ReturnType.GetGenericTypeDefinition() == typeof(Task<>))
            {
                return GetConcreteBuilderType(typeof(AsyncTaskMethodBuilder<>));
            }
            // Fallback to AsyncTaskMethodBuilder if the benchmark return type is Task or any awaitable type that is not a custom task-like type.
            return typeof(AsyncTaskMethodBuilder);

            Type GetBuilderTypeFromUserSpecifiedAsyncType(Type asyncType)
            {
                if (asyncType.GetAsyncMethodBuilderAttribute() is { } typeAttr
                    && typeAttr.GetType().GetProperty(nameof(AsyncMethodBuilderAttribute.BuilderType), BindingFlags.Public | BindingFlags.Instance)?.GetValue(typeAttr) is Type typeBuilderType)
                {
                    return GetConcreteBuilderType(typeBuilderType);
                }
                // Task and Task<T> are not annotated with their builder type, the C# compiler special-cases them.
                if (asyncType == typeof(Task))
                {
                    return typeof(AsyncTaskMethodBuilder);
                }
                if (asyncType.IsGenericType && asyncType.GetGenericTypeDefinition() == typeof(Task<>))
                {
                    return typeof(AsyncTaskMethodBuilder<>).MakeGenericType([asyncType.GetGenericArguments()[0]]);
                }
                throw new NotSupportedException($"AsyncMethodBuilderAttribute not found on type {asyncType.GetDisplayName()} from {Descriptor.DisplayInfo}");
            }

            Type GetConcreteBuilderType(Type builderType)
            {
                if (!builderType.IsGenericTypeDefinition)
                {
                    return builderType;
                }
                if (builderType.GetGenericArguments().Length != 1)
                {
                    throw new NotSupportedException($"AsyncMethodBuilder {builderType.GetDisplayName()} has generic arity greater than 1.");
                }
                var resultType = Descriptor.WorkloadMethod.ReturnType
                    .GetMethod(nameof(Task.GetAwaiter), BindingFlags.Public | BindingFlags.Instance)
                    .ReturnType
                    .GetMethod(nameof(TaskAwaiter.GetResult), BindingFlags.Public | BindingFlags.Instance)
                    .ReturnType;
                return builderType.MakeGenericType([resultType]);
            }
        }

        private void EmitWorkload()
        {
            var asyncMethodBuilderType = GetWorkloadCoreAsyncMethodBuilderType();
            var builderInfo = BeginAsyncStateMachineTypeBuilder(WorkloadCoreMethodName, asyncMethodBuilderType, runnableBuilder);
            var (asyncStateMachineTypeBuilder, publicFields, (ilBuilder, endTryLabel, returnLabel, stateLocal, thisLocal, returnDefaultLocal)) = builderInfo;
            var (stateField, builderField, _) = publicFields;
            var startedClockField = asyncStateMachineTypeBuilder.DefineField(
                "<startedClock>5__2",
                typeof(StartedClock),
                FieldAttributes.Private
            );
            var workloadContinuerAwaiterField = asyncStateMachineTypeBuilder.DefineField(
                "<>u__1",
                typeof(object),
                FieldAttributes.Private
            );
            var benchmarkAwaiterField = asyncStateMachineTypeBuilder.DefineField(
                "<>u__2",
                Descriptor.WorkloadMethod.ReturnType
                    .GetMethod(nameof(Task.GetAwaiter), BindingFlags.Public | BindingFlags.Instance)
                    .ReturnType,
                FieldAttributes.Private
            );
            EmitMoveNextImpl();
            var asyncStateMachineType = CompleteAsyncStateMachineType(asyncMethodBuilderType, builderInfo);

            var workloadCoreMethod = EmitAsyncCallerStub(WorkloadCoreMethodName, asyncStateMachineType, publicFields);

            var startWorkloadMethod = EmitAsyncSingleCall(StartWorkloadMethodName, typeof(AsyncVoidMethodBuilder), workloadCoreMethod, false);

            var noUnrollMethod = EmitNoUnrollMethod();
            EmitUnrollMethod();

            void EmitMoveNextImpl()
            {
                /*
                    .locals init (
		                [3] class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource,
		                [4] valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats> awaitable,
		                [5] valuetype [System.Runtime]System.Runtime.CompilerServices.ValueTaskAwaiter`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats>,
		                [6] int64,
		                [7] class [System.Runtime]System.Exception e,
	                )
                 */
                var workloadContinuerLocal = ilBuilder.DeclareLocal(typeof(WorkloadContinuerAndValueTaskSource));
                var benchmarkAwaitableLocal = Descriptor.WorkloadMethod.ReturnType.IsValueType
                    ? ilBuilder.DeclareLocal(Descriptor.WorkloadMethod.ReturnType)
                    : null;
                var benchmarkAwaiterLocal = ilBuilder.DeclareLocal(benchmarkAwaiterField.FieldType);
                var invokeCountLocal = ilBuilder.DeclareLocal(typeof(long));
                var exceptionLocal = ilBuilder.DeclareLocal(typeof(Exception));

                var whileTrueLabel = ilBuilder.DefineLabel(); // IL_001d
                var workloadContinuationLabel = ilBuilder.DefineLabel(); // IL_0059
                var workloadContinuationGetResultLabel = ilBuilder.DefineLabel(); // IL_0075
                var benchmarkContinuationLabel = ilBuilder.DefineLabel(); // IL_00f0
                var benchmarkContinuationGetResultLabel = ilBuilder.DefineLabel(); // IL_010d
                var startClockLabel = ilBuilder.DefineLabel(); // IL_009a
                var callBenchmarkLoopLabel = ilBuilder.DefineLabel(); // IL_0115
                var callBenchmarkLabel = ilBuilder.DefineLabel(); // IL_00b2

                // Not sure why Roslyn emits this, but we match it exactly.
                /*
					IL_000e: ldloc.0
					// _ = 1;
					IL_000f: ldc.i4.1
					IL_0010: pop
					IL_0011: pop
					IL_0012: nop
				 */
                ilBuilder.EmitLdloc(stateLocal);
                ilBuilder.Emit(OpCodes.Ldc_I4_1);
                ilBuilder.Emit(OpCodes.Pop);
                ilBuilder.Emit(OpCodes.Pop);
                ilBuilder.Emit(OpCodes.Nop);

                ilBuilder.BeginExceptionBlock();
				{
                    /*
					    // if (num != 0)
                        IL_0013: ldloc.0
                        IL_0014: brfalse.s IL_0059
                     */
                    ilBuilder.EmitLdloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Brfalse_S, workloadContinuationLabel);

                    /*
                        // if (num != 1)
                        IL_0016: ldloc.0
                        IL_0017: ldc.i4.1
                        IL_0018: beq IL_00f0
                     */
                    ilBuilder.EmitLdloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Ldc_I4_1);
                    ilBuilder.Emit(OpCodes.Beq, benchmarkContinuationLabel);

                    /*
                        // awaiter2 = runnable_.__fieldsContainer.workloadContinuerAndValueTaskSource.GetAwaiter();
                        IL_001d: ldloc.1
                        IL_001e: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
                        IL_0023: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
                        IL_0028: callvirt instance class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::GetAwaiter()
                        IL_002d: stloc.3
                     */
                    ilBuilder.MarkLabel(whileTrueLabel);
                    ilBuilder.EmitLdloc(thisLocal);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                    ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadContinuerAndValueTaskSource).GetMethod(nameof(WorkloadContinuerAndValueTaskSource.GetAwaiter), BindingFlags.Public | BindingFlags.Instance));
                    ilBuilder.EmitStloc(workloadContinuerLocal);
                    /*
                        // if (!awaiter2.IsCompleted)
                        IL_002e: ldloc.3
                        IL_002f: callvirt instance bool [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::get_IsCompleted()
                        IL_0034: brtrue.s IL_0075
                     */
                    ilBuilder.EmitLdloc(workloadContinuerLocal);
                    ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadContinuerAndValueTaskSource).GetProperty(nameof(WorkloadContinuerAndValueTaskSource.IsCompleted), BindingFlags.Public | BindingFlags.Instance).GetMethod);
                    ilBuilder.Emit(OpCodes.Brtrue_S, workloadContinuationGetResultLabel);
                    /*
                        // num = (<>1__state = 0);
                        IL_0036: ldarg.0
                        IL_0037: ldc.i4.0
                        IL_0038: dup
                        IL_0039: stloc.0
                        IL_003a: stfld int32 BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>1__state'
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_0);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);
                    /*
                        // <>u__1 = awaiter2;
                        IL_003f: ldarg.0
                        IL_0040: ldloc.3
                        IL_0041: stfld object BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>u__1'
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitLdloc(workloadContinuerLocal);
                    ilBuilder.Emit(OpCodes.Stfld, workloadContinuerAwaiterField);
                    /*
                        // <>t__builder.AwaitUnsafeOnCompleted<WorkloadContinuerAndValueTaskSource, <__WorkloadCore>d__17>(ref awaiter2, ref this);
                        IL_0046: ldarg.0
                        IL_0047: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats> BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>t__builder'
                        IL_004c: ldloca.s 3
                        IL_004e: ldarg.0
                        IL_004f: call instance void valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats>::AwaitUnsafeOnCompleted<class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource, valuetype BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'>(!!0&, !!1&)
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldflda, builderField);
                    ilBuilder.EmitLdloca(workloadContinuerLocal);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Call, GetAwaitOnCompletedMethod(asyncMethodBuilderType, typeof(WorkloadContinuerAndValueTaskSource), asyncStateMachineTypeBuilder));
                    /*
                        // return;
                        IL_0054: leave IL_01a7
                     */
                    ilBuilder.Emit(OpCodes.Leave, returnLabel);

                    /*
                        // WorkloadContinuerAndValueTaskSource awaiter2 = (WorkloadContinuerAndValueTaskSource)<>u__1;
                        IL_0059: ldarg.0
                        IL_005a: ldfld object BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>u__1'
                        IL_005f: castclass [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource
                        IL_0064: stloc.3
                     */
                    ilBuilder.MarkLabel(workloadContinuationLabel);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAwaiterField);
                    ilBuilder.Emit(OpCodes.Castclass, typeof(WorkloadContinuerAndValueTaskSource));
                    ilBuilder.EmitStloc(workloadContinuerLocal);
                    /*
                        // <>u__1 = null;
                        IL_0065: ldarg.0
                        IL_0066: ldnull
                        IL_0067: stfld object BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>u__1'
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitSetFieldToDefault(workloadContinuerAwaiterField);
                    /*
                        // num = (<>1__state = -1);
                        IL_006c: ldarg.0
                        IL_006d: ldc.i4.m1
                        IL_006e: dup
                        IL_006f: stloc.0
                        IL_0070: stfld int32 BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>1__state'
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_M1);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);

                    /*
                        // awaiter2.GetResult();
                        IL_0075: ldloc.3
                        IL_0076: callvirt instance void [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::GetResult()
                     */
                    ilBuilder.MarkLabel(workloadContinuationGetResultLabel);
                    ilBuilder.EmitLdloc(workloadContinuerLocal);
                    ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadContinuerAndValueTaskSource).GetMethod(nameof(WorkloadContinuerAndValueTaskSource.GetResult), BindingFlags.Public | BindingFlags.Instance));
                    /*
                        // if (!runnable_.__fieldsContainer.workloadContinuerAndValueTaskSource.IsCompleted)
                        IL_007b: ldloc.1
                        IL_007c: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
                        IL_0081: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
                        IL_0086: callvirt instance bool [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::get_IsCompleted()
                        IL_008b: brfalse.s IL_009a
                     */
                    ilBuilder.EmitLdloc(thisLocal);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                    ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadContinuerAndValueTaskSource).GetProperty(nameof(WorkloadContinuerAndValueTaskSource.IsCompleted), BindingFlags.Public | BindingFlags.Instance).GetMethod);
                    ilBuilder.Emit(OpCodes.Brfalse_S, startClockLabel);

                    /*
                        // result = default(GcStats);
                        IL_008d: ldloca.s 2
                        IL_008f: initobj [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats
                     */
                    ilBuilder.MaybeEmitSetLocalToDefault(returnDefaultLocal);
                    /*
                        IL_0095: leave IL_0193
                     */
                    ilBuilder.Emit(OpCodes.Leave, endTryLabel);

                    /*
                        // <startedClock>5__2 = ClockExtensions.Start(runnable_.__fieldsContainer.clock);
                        IL_009a: ldarg.0
                        IL_009b: ldloc.1
                        IL_009c: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
                        IL_00a1: ldfld class [Perfolizer]Perfolizer.Horology.IClock BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::clock
                        IL_00a6: call valuetype [Perfolizer]Perfolizer.Horology.StartedClock [Perfolizer]Perfolizer.Horology.ClockExtensions::Start(class [Perfolizer]Perfolizer.Horology.IClock)
                        IL_00ab: stfld valuetype [Perfolizer]Perfolizer.Horology.StartedClock BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<startedClock>5__2'
                     */
                    ilBuilder.MarkLabel(startClockLabel);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitLdloc(thisLocal);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldfld, clockField);
                    ilBuilder.Emit(OpCodes.Call, GetStartClockMethod());
                    ilBuilder.Emit(OpCodes.Stfld, startedClockField);
                    /*
                        // goto IL_0115;
                        IL_00b0: br.s IL_0115
                     */
                    ilBuilder.Emit(OpCodes.Br, callBenchmarkLoopLabel);

                    /*
                        // awaiter = ((AllSetupAndCleanupAttributeBenchmarksTask)runnable_).Benchmark2().GetAwaiter();
                        IL_00b2: ldloc.1
                        IL_00b3: call instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats> [BenchmarkDotNet.IntegrationTests]BenchmarkDotNet.IntegrationTests.AllSetupAndCleanupTest/AllSetupAndCleanupAttributeBenchmarksTask::Benchmark2()
                        IL_00b8: stloc.s 4
                        IL_00ba: ldloca.s 4
                     */
                    ilBuilder.MarkLabel(callBenchmarkLabel);
                    if (!Descriptor.WorkloadMethod.IsStatic)
                    {
                        ilBuilder.EmitLdloc(thisLocal);
                    }
                    EmitLoadArgFieldsForCall(ilBuilder, thisLocal);
                    ilBuilder.Emit(OpCodes.Call, Descriptor.WorkloadMethod);
                    if (benchmarkAwaitableLocal == null)
                    {
                        ilBuilder.Emit(OpCodes.Callvirt, Descriptor.WorkloadMethod.ReturnType.GetMethod(nameof(Task.GetAwaiter), BindingFlags.Public | BindingFlags.Instance));
                    }
                    else
                    {
                        ilBuilder.EmitStloc(benchmarkAwaitableLocal);
                        ilBuilder.EmitLdloca(benchmarkAwaitableLocal);
                        ilBuilder.Emit(OpCodes.Call, Descriptor.WorkloadMethod.ReturnType.GetMethod(nameof(Task.GetAwaiter), BindingFlags.Public | BindingFlags.Instance));
                    }
                    /*
                        // if (!awaiter.IsCompleted)
                        IL_00bc: call instance valuetype [System.Runtime]System.Runtime.CompilerServices.ValueTaskAwaiter`1<!0> valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats>::GetAwaiter()
                        IL_00c1: stloc.s 5
                        IL_00c3: ldloca.s 5
                        IL_00c5: call instance bool valuetype [System.Runtime]System.Runtime.CompilerServices.ValueTaskAwaiter`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats>::get_IsCompleted()
                        IL_00ca: brtrue.s IL_010d
                     */
                    ilBuilder.EmitStloc(benchmarkAwaiterLocal);
                    ilBuilder.EmitLdloca(benchmarkAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Call, benchmarkAwaiterField.FieldType.GetProperty(nameof(TaskAwaiter.IsCompleted), BindingFlags.Public | BindingFlags.Instance).GetMethod);
                    ilBuilder.Emit(OpCodes.Brtrue_S, benchmarkContinuationGetResultLabel);

                    /*
                        // num = (<>1__state = 1);
                        IL_00cc: ldarg.0
                        IL_00cd: ldc.i4.1
                        IL_00ce: dup
                        IL_00cf: stloc.0
                        IL_00d0: stfld int32 BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>1__state'
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_1);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);
                    /*
                        // <>u__2 = awaiter;
                        IL_00d5: ldarg.0
                        IL_00d6: ldloc.s 5
                        IL_00d8: stfld valuetype [System.Runtime]System.Runtime.CompilerServices.ValueTaskAwaiter`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats> BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>u__2'
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitLdloc(benchmarkAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Stfld, benchmarkAwaiterField);
                    /*
                        // <>t__builder.AwaitUnsafeOnCompleted(ref awaiter, ref this);
                        IL_00dd: ldarg.0
                        IL_00de: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats> BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>t__builder'
                        IL_00e3: ldloca.s 5
                        IL_00e5: ldarg.0
                        IL_00e6: call instance void valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats>::AwaitUnsafeOnCompleted<valuetype [System.Runtime]System.Runtime.CompilerServices.ValueTaskAwaiter`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats>, valuetype BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'>(!!0&, !!1&)
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldflda, builderField);
                    ilBuilder.EmitLdloca(benchmarkAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Call, GetAwaitOnCompletedMethod(asyncMethodBuilderType, benchmarkAwaiterField.FieldType, asyncStateMachineTypeBuilder));
                    /*
                        // return;
                        IL_00eb: leave IL_01a7
                     */
                    ilBuilder.Emit(OpCodes.Leave, returnLabel);

                    /*
                        // awaiter = <>u__2;
                        IL_00f0: ldarg.0
                        IL_00f1: ldfld valuetype [System.Runtime]System.Runtime.CompilerServices.ValueTaskAwaiter`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats> BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>u__2'
                        IL_00f6: stloc.s 5
                     */
                    ilBuilder.MarkLabel(benchmarkContinuationLabel);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldfld, benchmarkAwaiterField);
                    ilBuilder.EmitStloc(benchmarkAwaiterLocal);
                    /*
                        // <>u__2 = default(ValueTaskAwaiter<GcStats>);
                        IL_00f8: ldarg.0
                        IL_00f9: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.ValueTaskAwaiter`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats> BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>u__2'
                        IL_00fe: initobj valuetype [System.Runtime]System.Runtime.CompilerServices.ValueTaskAwaiter`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats>
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitSetFieldToDefault(benchmarkAwaiterField);
                    /*
                        // num = (<>1__state = -1);
                        IL_0104: ldarg.0
                        IL_0105: ldc.i4.m1
                        IL_0106: dup
                        IL_0107: stloc.0
                        IL_0108: stfld int32 BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<>1__state'
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_M1);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);

                    /*
                        // awaiter.GetResult();
                        IL_010d: ldloca.s 5
                        IL_010f: call instance !0 valuetype [System.Runtime]System.Runtime.CompilerServices.ValueTaskAwaiter`1<valuetype [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats>::GetResult()
                        IL_0114: pop
                     */
                    ilBuilder.MarkLabel(benchmarkContinuationGetResultLabel);
                    ilBuilder.EmitLdloca(benchmarkAwaiterLocal);
                    var benchmarkAwaiterGetResultMethod = benchmarkAwaiterField.FieldType.GetMethod(nameof(TaskAwaiter.GetResult), BindingFlags.Public | BindingFlags.Instance);
                    ilBuilder.Emit(OpCodes.Call, benchmarkAwaiterGetResultMethod);
                    if (benchmarkAwaiterGetResultMethod.ReturnType != typeof(void))
                    {
                        ilBuilder.Emit(OpCodes.Pop);
                    }

                    /*
                        // if (--runnable_.__fieldsContainer.invokeCount >= 0)
                        IL_0115: ldloc.1
                        IL_0116: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
                        IL_011b: ldflda int64 BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::invokeCount
                        IL_0120: dup
                        IL_0121: ldind.i8
                        IL_0122: ldc.i4.1
                        IL_0123: conv.i8
                        IL_0124: sub
                        IL_0125: stloc.s 6
                        IL_0127: ldloc.s 6
                        IL_0129: stind.i8
                     */
                    ilBuilder.MarkLabel(callBenchmarkLoopLabel);
                    ilBuilder.EmitLdloc(thisLocal);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldflda, invokeCountField);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.Emit(OpCodes.Ldind_I8);
                    ilBuilder.Emit(OpCodes.Ldc_I4_1);
                    ilBuilder.Emit(OpCodes.Conv_I8);
                    ilBuilder.Emit(OpCodes.Sub);
                    ilBuilder.EmitStloc(invokeCountLocal);
                    ilBuilder.EmitLdloc(invokeCountLocal);
                    ilBuilder.Emit(OpCodes.Stind_I8);
                    /*
                        // runnable_.__fieldsContainer.workloadContinuerAndValueTaskSource.SetResult(<startedClock>5__2.GetElapsed());
                        IL_012a: ldloc.s 6
                        IL_012c: ldc.i4.0
                        IL_012d: conv.i8
                        IL_012e: bge.s IL_00b2
                     */
                    ilBuilder.EmitLdloc(invokeCountLocal);
                    ilBuilder.Emit(OpCodes.Ldc_I4_0);
                    ilBuilder.Emit(OpCodes.Conv_I8);
                    ilBuilder.Emit(OpCodes.Bge, callBenchmarkLabel);

                    /*
                        IL_0130: ldloc.1
                        IL_0131: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
                        IL_0136: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
                        IL_013b: ldarg.0
                        IL_013c: ldflda valuetype [Perfolizer]Perfolizer.Horology.StartedClock BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<startedClock>5__2'
                        IL_0141: call instance valuetype [Perfolizer]Perfolizer.Horology.ClockSpan [Perfolizer]Perfolizer.Horology.StartedClock::GetElapsed()
                        IL_0146: callvirt instance void [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::SetResult(valuetype [Perfolizer]Perfolizer.Horology.ClockSpan)
                     */
                    ilBuilder.EmitLdloc(thisLocal);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldflda, startedClockField);
                    ilBuilder.Emit(OpCodes.Call, typeof(StartedClock).GetMethod(nameof(StartedClock.GetElapsed), BindingFlags.Public | BindingFlags.Instance));
                    ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadContinuerAndValueTaskSource).GetMethod(nameof(WorkloadContinuerAndValueTaskSource.SetResult), [typeof(ClockSpan)]));
                    /*
                        // <startedClock>5__2 = default(StartedClock);
                        IL_014b: ldarg.0
                        IL_014c: ldflda valuetype [Perfolizer]Perfolizer.Horology.StartedClock BenchmarkDotNet.Autogenerated.Runnable_1/'<__WorkloadCore>d__17'::'<startedClock>5__2'
                        IL_0151: initobj [Perfolizer]Perfolizer.Horology.StartedClock
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitSetFieldToDefault(startedClockField);
                    /*
                        // goto IL_001d;
                        IL_0157: br IL_001d
                     */
                    ilBuilder.Emit(OpCodes.Br, whileTrueLabel);
                }
                // end .try
                ilBuilder.BeginCatchBlock(typeof(Exception));
                {
                    /*
                        // catch (Exception exception)
                        IL_015c: stloc.s 7
                     */
                    ilBuilder.EmitStloc(exceptionLocal);
                    /*
                        // runnable_.__fieldsContainer.workloadContinuerAndValueTaskSource.SetException(exception);
                        IL_015e: ldloc.1
                        IL_015f: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
                        IL_0164: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
                        IL_0169: ldloc.s 7
                        IL_016b: callvirt instance void [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::SetException(class [System.Runtime]System.Exception)
                     */
                    ilBuilder.EmitLdloc(thisLocal);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                    ilBuilder.EmitLdloc(exceptionLocal);
                    ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadContinuerAndValueTaskSource).GetMethod(nameof(WorkloadContinuerAndValueTaskSource.SetException), [typeof(Exception)]));
                    /*
                        // result = default(GcStats);
                        IL_0170: ldloca.s 2
                        IL_0172: initobj [BenchmarkDotNet]BenchmarkDotNet.Engines.GcStats
                        IL_0178: leave.s IL_0193
                     */
                    ilBuilder.MaybeEmitSetLocalToDefault(returnDefaultLocal);

                    ilBuilder.EndExceptionBlock();
                } // end handler
            }

            MethodInfo EmitNoUnrollMethod()
            {
                /*
                    // private ValueTask<ClockSpan> WorkloadActionNoUnroll(long invokeCount, IClock clock)
                    .method private hidebysig 
	                    instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> WorkloadActionNoUnroll (
		                    int64 invokeCount,
		                    class [Perfolizer]Perfolizer.Horology.IClock clock
	                    ) cil managed flags(0200)
                 */
                var methodBuilder = runnableBuilder
                    .DefineNonVirtualInstanceMethod(
                        WorkloadActionNoUnrollMethodName,
                        MethodAttributes.Private,
                        EmitParameterInfo.CreateReturnParameter(typeof(ValueTask<ClockSpan>)),
                        [
                            new EmitParameterInfo(0, InvokeCountParamName, typeof(long)),
                            new EmitParameterInfo(1, ClockParamName, typeof(IClock))
                        ]
                    )
                    .SetAggressiveOptimizationImplementationFlag();

                var ilBuilder = methodBuilder.GetILGenerator();

                var callContinueLabel = ilBuilder.DefineLabel(); // IL_003b

                /*
                    // __fieldsContainer.invokeCount = invokeCount;
	                IL_0000: ldarg.0
	                IL_0001: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_0006: ldarg.1
	                IL_0007: stfld int64 BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::invokeCount
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Ldarg_1);
                ilBuilder.Emit(OpCodes.Stfld, invokeCountField);
                /*
	                // __fieldsContainer.clock = clock;
	                IL_000c: ldarg.0
	                IL_000d: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_0012: ldarg.2
	                IL_0013: stfld class [Perfolizer]Perfolizer.Horology.IClock BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::clock
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Ldarg_2);
                ilBuilder.Emit(OpCodes.Stfld, clockField);
                /*
	                // if (__fieldsContainer.workloadContinuerAndValueTaskSource == null)
	                IL_0018: ldarg.0
	                IL_0019: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_001e: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
	                IL_0023: brtrue.s IL_003b
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                ilBuilder.Emit(OpCodes.Brtrue_S, callContinueLabel);

                /*
	                // __fieldsContainer.workloadContinuerAndValueTaskSource = new WorkloadContinuerAndValueTaskSource();
	                IL_0025: ldarg.0
	                IL_0026: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_002b: newobj instance void [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::.ctor()
	                IL_0030: stfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Newobj, typeof(WorkloadContinuerAndValueTaskSource).GetConstructor([]));
                ilBuilder.Emit(OpCodes.Stfld, workloadContinuerAndValueTaskSourceField);
                /*
	                // __StartWorkload();
	                IL_0035: ldarg.0
	                IL_0036: call instance void BenchmarkDotNet.Autogenerated.Runnable_1::__StartWorkload()
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Call, startWorkloadMethod);

                /*
	                // return __fieldsContainer.workloadContinuerAndValueTaskSource.Continue();
	                IL_003b: ldarg.0
	                IL_003c: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_0041: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
	                IL_0046: callvirt instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::Continue()
	                IL_004b: ret
                 */
                ilBuilder.MarkLabel(callContinueLabel);
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadContinuerAndValueTaskSource).GetMethod(nameof(WorkloadContinuerAndValueTaskSource.Continue), BindingFlags.Public | BindingFlags.Instance));
                ilBuilder.Emit(OpCodes.Ret);

                return methodBuilder;
            }

            void EmitUnrollMethod()
            {
                /*
                    // private ValueTask<ClockSpan> WorkloadActionUnroll(long invokeCount, IClock clock)
                    .method private hidebysig 
	                    instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> WorkloadActionUnroll (
		                    int64 invokeCount,
		                    class [Perfolizer]Perfolizer.Horology.IClock clock
	                    ) cil managed flags(0200)
                 */
                var methodBuilder = runnableBuilder
                    .DefineNonVirtualInstanceMethod(
                        WorkloadActionUnrollMethodName,
                        MethodAttributes.Private,
                        EmitParameterInfo.CreateReturnParameter(typeof(ValueTask<ClockSpan>)),
                        [
                            new EmitParameterInfo(0, InvokeCountParamName, typeof(long)),
                            new EmitParameterInfo(1, ClockParamName, typeof(IClock))
                        ]
                    )
                    .SetAggressiveOptimizationImplementationFlag();

                var ilBuilder = methodBuilder.GetILGenerator();

                /*
                    // return WorkloadActionNoUnroll(invokeCount * 16, clock);
	                IL_0000: ldarg.0
	                IL_0001: ldarg.1
	                IL_0002: ldc.i4.s 16
	                IL_0004: conv.i8
	                IL_0005: mul
	                IL_0006: ldarg.2
	                IL_0007: call instance valuetype [System.Threading.Tasks.Extensions]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> BenchmarkDotNet.Autogenerated.Runnable_0::WorkloadActionNoUnroll(int64, class [Perfolizer]Perfolizer.Horology.IClock)
	                IL_000c: ret
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldarg_1);
                ilBuilder.EmitLdc_I4(jobUnrollFactor);
                ilBuilder.Emit(OpCodes.Conv_I8);
                ilBuilder.Emit(OpCodes.Mul);
                ilBuilder.Emit(OpCodes.Ldarg_2);
                ilBuilder.Emit(OpCodes.Call, noUnrollMethod);
                ilBuilder.Emit(OpCodes.Ret);
            }
        }
    }
}