using BenchmarkDotNet.Helpers.Reflection.Emit;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using static BenchmarkDotNet.Toolchains.InProcess.Emit.Implementation.RunnableConstants;

namespace BenchmarkDotNet.Toolchains.InProcess.Emit.Implementation;

partial class RunnableEmitter
{
    // Roslyn generates ordinals in declaration order of every member.
    // We don't necessarily emit members in the same order (or at all in the case of Runnable_#.Run), so we map it to the expected Roslyn ordinal.
    // This doesn't really matter for the runtime, but it helps with the NaiveRunnableEmitDiff tests.
    private readonly Dictionary<string, int> s_asyncMethodToOrdinalMap = new()
    {
        { GlobalSetupMethodName, 4 },
        { GlobalCleanupMethodName, 5 },
        { IterationSetupMethodName, 6 },
        { IterationCleanupMethodName, 7 },
        { OverheadActionUnrollMethodName, 12 },
        { OverheadActionNoUnrollMethodName, 13 },
        { WorkloadActionUnrollMethodName, 14 },
        { WorkloadActionNoUnrollMethodName, 15 },
        { StartWorkloadMethodName, 16 },
        { WorkloadCoreMethodName, 17 },
    };

    private record struct AsyncStateMachineFields(FieldInfo StateField, FieldInfo BuilderField, FieldInfo? ThisField);
    private record struct AsyncStateMachineMoveNextInfo(ILGenerator IlBuilder, Label EndTryLabel, Label ReturnLabel, LocalBuilder StateLocal, LocalBuilder? ThisLocal, LocalBuilder? ReturnDefaultLocal);
    private record struct AsyncStateMachineBuilderInfo(TypeBuilder TypeBuilder, AsyncStateMachineFields PublicFields, AsyncStateMachineMoveNextInfo MoveNextInfo);

    private MethodInfo EmitAsyncCallerStub(string methodName, Type asyncStateMachineType, AsyncStateMachineFields asyncStateMachineFields)
    {
        var (stateField, builderField, thisField) = asyncStateMachineFields;
        var asyncMethodBuilderType = builderField.FieldType;

        // AsyncVoidMethodBuilder for `async void` has no Task property.
        var taskGetMethod = asyncMethodBuilderType.GetProperty(nameof(AsyncTaskMethodBuilder.Task), BindingFlags.Public | BindingFlags.Instance)?.GetMethod;
        /*
            .method private hidebysig 
               instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask __GlobalSetup () cil managed flags(0200)
        */
        var methodBuilder = runnableBuilder
            .DefineNonVirtualInstanceMethod(
                methodName,
                MethodAttributes.Private,
                taskGetMethod?.ReturnParameter ?? EmitParameterInfo.CreateReturnVoidParameter()
            )
            .SetAggressiveOptimizationImplementationFlag();

        // [AsyncStateMachine(typeof(<__GlobalSetup>d__4))]
        var attrCtor = typeof(AsyncStateMachineAttribute).GetConstructor([typeof(Type)])
            ?? throw new MissingMemberException(nameof(AsyncStateMachineAttribute));
        methodBuilder.SetCustomAttribute(new CustomAttributeBuilder(attrCtor, [asyncStateMachineType]));

        ILGenerator ilBuilder = methodBuilder.GetILGenerator();
        /*
            .locals init (
                [0] valuetype BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'
            )
         */
        var asyncStateMachineLocal = ilBuilder.DeclareLocal(asyncStateMachineType);
        /*
            // stateMachine.<>t__builder = AsyncTaskMethodBuilder.Create();
            IL_0000: ldloca.s 0
            IL_0002: call valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncTaskMethodBuilder [System.Runtime]System.Runtime.CompilerServices.AsyncTaskMethodBuilder::Create()
            IL_0007: stfld valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncTaskMethodBuilder BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>t__builder'
         */
        ilBuilder.EmitLdloca(asyncStateMachineLocal);
        ilBuilder.Emit(OpCodes.Call, asyncMethodBuilderType.GetMethod(nameof(AsyncTaskMethodBuilder.Create), BindingFlags.Public | BindingFlags.Static)!);
        ilBuilder.Emit(OpCodes.Stfld, builderField);
        if (thisField is not null)
        {
            /*
                // stateMachine.<>4__this = this;
                IL_000c: ldloca.s 0
                IL_000e: ldarg.0
                IL_000f: stfld class BenchmarkDotNet.Autogenerated.Runnable_0 BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>4__this'
             */
            ilBuilder.EmitLdloca(asyncStateMachineLocal);
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Stfld, thisField);
        }
        /*
            // stateMachine.<>1__state = -1;
            IL_0014: ldloca.s 0
            IL_0016: ldc.i4.m1
            IL_0017: stfld int32 BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>1__state'
         */
        ilBuilder.EmitLdloca(asyncStateMachineLocal);
        ilBuilder.Emit(OpCodes.Ldc_I4_M1);
        ilBuilder.Emit(OpCodes.Stfld, stateField);
        /*
            // stateMachine.<>t__builder.Start(ref stateMachine);
            IL_001c: ldloca.s 0
            IL_001e: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncTaskMethodBuilder BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>t__builder'
            IL_0023: ldloca.s 0
            IL_0025: call instance void [System.Runtime]System.Runtime.CompilerServices.AsyncTaskMethodBuilder::Start<valuetype BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'>(!!0&)
         */
        ilBuilder.EmitLdloca(asyncStateMachineLocal);
        ilBuilder.Emit(OpCodes.Ldflda, builderField);
        ilBuilder.EmitLdloca(asyncStateMachineLocal);
        var startMethod = asyncMethodBuilderType
            .GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Single(method => method.IsGenericMethod && method.Name == nameof(AsyncTaskMethodBuilder.Start))
            .MakeGenericMethod(asyncStateMachineType);
        ilBuilder.Emit(OpCodes.Call, startMethod);

        if (taskGetMethod != null)
        {
            /*
                // return stateMachine.<>t__builder.Task;
                IL_002a: ldloca.s 0
                IL_002c: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncTaskMethodBuilder BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>t__builder'
                IL_0031: call instance class [System.Runtime]System.Threading.Tasks.Task [System.Runtime]System.Runtime.CompilerServices.AsyncTaskMethodBuilder::get_Task()
             */
            ilBuilder.EmitLdloca(asyncStateMachineLocal);
            ilBuilder.Emit(OpCodes.Ldflda, builderField);
            ilBuilder.Emit(OpCodes.Call, taskGetMethod);
        }
        /*
            IL_0036: ret
         */
        ilBuilder.Emit(OpCodes.Ret);

        return methodBuilder;
    }

    private AsyncStateMachineBuilderInfo BeginAsyncStateMachineTypeBuilder(string callerMethodName, Type asyncMethodBuilderType, Type? thisType)
    {
        /*
            [StructLayout(LayoutKind.Auto)]
            [CompilerGenerated]
            private struct <__GlobalSetup>d__4 : IAsyncStateMachine
         */
        int ordinal = s_asyncMethodToOrdinalMap[callerMethodName];
        var asyncStateMachineTypeBuilder = runnableBuilder.DefineNestedType(
            $"<{callerMethodName}>d__{ordinal}",
            TypeAttributes.NestedPrivate | TypeAttributes.AutoLayout | TypeAttributes.Sealed | TypeAttributes.BeforeFieldInit,
            typeof(ValueType));
        nestedTypeBuilders.Add(asyncStateMachineTypeBuilder);

        asyncStateMachineTypeBuilder.AddInterfaceImplementation(typeof(IAsyncStateMachine));

        var attrCtor = typeof(CompilerGeneratedAttribute).GetConstructor([])
            ?? throw new MissingMemberException(nameof(CompilerGeneratedAttribute));
        asyncStateMachineTypeBuilder.SetCustomAttribute(new CustomAttributeBuilder(attrCtor, []));

        /*
            .field public int32 '<>1__state'
            .field public valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder '<>t__builder'
            .field public class BenchmarkDotNet.Autogenerated.Runnable_0 '<>4__this'
         */
        var stateField = asyncStateMachineTypeBuilder.DefineField("<>1__state", typeof(int), FieldAttributes.Public);
        var builderField = asyncStateMachineTypeBuilder.DefineField("<>t__builder", asyncMethodBuilderType, FieldAttributes.Public);
        var thisField = thisType is not null
            ? asyncStateMachineTypeBuilder.DefineField("<>4__this", thisType, FieldAttributes.Public)
            : null;

        var moveNextInfo = BeginEmitMoveNext();
        EmitSetStateMachine();

        return new(asyncStateMachineTypeBuilder, new(stateField, builderField, thisField), moveNextInfo);

        AsyncStateMachineMoveNextInfo BeginEmitMoveNext()
        {
            /*
                .method private final hidebysig newslot virtual 
                    instance void MoveNext () cil managed flags(0200) 
             */
            var methodBuilder = asyncStateMachineTypeBuilder
                .DefineMethod(
                    nameof(IAsyncStateMachine.MoveNext),
                    MethodAttributes.Private | MethodAttributes.Final | MethodAttributes.HideBySig | MethodAttributes.NewSlot | MethodAttributes.Virtual,
                    typeof(void),
                    []
                )
                .SetAggressiveOptimizationImplementationFlag();

            /*
                .override method instance void [System.Runtime]System.Runtime.CompilerServices.IAsyncStateMachine::MoveNext()
             */
            asyncStateMachineTypeBuilder.DefineMethodOverride(
                methodBuilder,
                typeof(IAsyncStateMachine).GetMethod(nameof(IAsyncStateMachine.MoveNext))!
            );

            var ilBuilder = methodBuilder.GetILGenerator();

            var stateLocal = ilBuilder.DeclareLocal(typeof(int));
            var thisLocal = thisType is not null
                ? ilBuilder.DeclareLocal(thisType)
                : null;
            var returnDefaultLocal = asyncMethodBuilderType.GetMethod(nameof(AsyncTaskMethodBuilder.SetResult), BindingFlags.Public | BindingFlags.Instance)!.GetParameters() is [var setResultParam]
                ? ilBuilder.DeclareLocal(setResultParam.ParameterType)
                : null;

            var endTryLabel = ilBuilder.DefineLabel(); // IL_0082
            var returnLabel = ilBuilder.DefineLabel(); // IL_0095

            /*
                // int num = <>1__state;
                IL_0000: ldarg.0
                IL_0001: ldfld int32 BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>1__state'
                IL_0006: stloc.0
             */
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Ldfld, stateField);
            ilBuilder.Emit(OpCodes.Stloc, stateLocal);
            if (thisField is not null)
            {
                /*
                    // Runnable_0 runnable_ = <>4__this;
                    IL_0007: ldarg.0
                    IL_0008: ldfld class BenchmarkDotNet.Autogenerated.Runnable_0 BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>4__this'
                    IL_000d: stloc.1
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldfld, thisField);
                ilBuilder.Emit(OpCodes.Stloc, thisLocal!);
            }

            ilBuilder.BeginExceptionBlock();
            {
                // Core impl emitted by caller.
            }
            // Catch block and the rest emitted by CompleteAsyncStateMachineTypeBuilder.

            return new(ilBuilder, endTryLabel, returnLabel, stateLocal, thisLocal, returnDefaultLocal);
        }

        void EmitSetStateMachine()
        {
            /*
                .method private final hidebysig newslot virtual 
                    instance void SetStateMachine (
                        class [System.Runtime]System.Runtime.CompilerServices.IAsyncStateMachine stateMachine
                    ) cil managed flags(0200) 
             */
            var methodBuilder = asyncStateMachineTypeBuilder
                .DefineMethod(
                    nameof(IAsyncStateMachine.SetStateMachine),
                    MethodAttributes.Private | MethodAttributes.Final | MethodAttributes.HideBySig | MethodAttributes.NewSlot | MethodAttributes.Virtual,
                    typeof(void),
                    [typeof(IAsyncStateMachine)]
                )
                .SetAggressiveOptimizationImplementationFlag();

            // [DebuggerHidden]
            var attrCtor = typeof(DebuggerHiddenAttribute).GetConstructor([])
                ?? throw new MissingMemberException(nameof(DebuggerHiddenAttribute));
            methodBuilder.SetCustomAttribute(new CustomAttributeBuilder(attrCtor, []));

            /*
                .override method instance void [System.Runtime]System.Runtime.CompilerServices.IAsyncStateMachine::SetStateMachine(class [System.Runtime]System.Runtime.CompilerServices.IAsyncStateMachine)
             */
            asyncStateMachineTypeBuilder.DefineMethodOverride(
                methodBuilder,
                typeof(IAsyncStateMachine).GetMethod(nameof(IAsyncStateMachine.SetStateMachine))!
            );

            var ilBuilder = methodBuilder.GetILGenerator();

            /*
                // <>t__builder.SetStateMachine(stateMachine);
                IL_0000: ldarg.0
                IL_0001: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>t__builder'
                IL_0006: ldarg.1
                IL_0007: call instance void [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder::SetStateMachine(class [System.Runtime]System.Runtime.CompilerServices.IAsyncStateMachine)
                IL_000c: ret
             */
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Ldflda, builderField);
            ilBuilder.Emit(OpCodes.Ldarg_1);
            ilBuilder.Emit(OpCodes.Call, asyncMethodBuilderType.GetMethod(nameof(AsyncTaskMethodBuilder.SetStateMachine), BindingFlags.Public | BindingFlags.Instance)!);
            ilBuilder.Emit(OpCodes.Ret);
        }
    }

    private Type CompleteAsyncStateMachineType(Type asyncMethodBuilderType, AsyncStateMachineBuilderInfo asyncStateMachineBuilderInfo)
    {
        var (asyncStateMachineTypeBuilder, (stateField, builderField, _), (ilBuilder, endTryLabel, returnLabel, _, _, returnDefaultLocal)) = asyncStateMachineBuilderInfo;

        var setResultMethod = asyncMethodBuilderType.GetMethod(nameof(AsyncTaskMethodBuilder.SetResult), BindingFlags.Public | BindingFlags.Instance)!;

        // end .try
        ilBuilder.BeginCatchBlock(typeof(Exception));
        {
            /*
                // catch (Exception exception)
                IL_006b: stloc.3
             */
            var exLocal = ilBuilder.DeclareLocal(typeof(Exception));
            ilBuilder.Emit(OpCodes.Stloc, exLocal);
            /*
                // <>1__state = -2;
                IL_006c: ldarg.0
                IL_006d: ldc.i4.s -2
                IL_006f: stfld int32 BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>1__state'
             */
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Ldc_I4_S, (sbyte) -2);
            ilBuilder.Emit(OpCodes.Stfld, stateField);
            /*
                // <>t__builder.SetException(exception);
                IL_0074: ldarg.0
                IL_0075: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>t__builder'
                IL_007a: ldloc.3
                IL_007b: call instance void [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder::SetException(class [System.Runtime]System.Exception)
             */
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Ldflda, builderField);
            ilBuilder.EmitLdloc(exLocal);
            ilBuilder.Emit(OpCodes.Call, asyncMethodBuilderType.GetMethod(nameof(AsyncTaskMethodBuilder.SetException), BindingFlags.Public | BindingFlags.Instance)!);

            ilBuilder.EndExceptionBlock();
        } // end handler
        /*
            // <>1__state = -2;
            IL_0082: ldarg.0
            IL_0083: ldc.i4.s -2
            IL_0085: stfld int32 BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>1__state'
         */
        // IL_0082:
        ilBuilder.MarkLabel(endTryLabel);

        ilBuilder.Emit(OpCodes.Ldarg_0);
        ilBuilder.Emit(OpCodes.Ldc_I4_S, (sbyte) -2);
        ilBuilder.Emit(OpCodes.Stfld, stateField);
        /*
            // <>t__builder.SetResult();
            IL_008a: ldarg.0
            IL_008b: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>t__builder'
            IL_0090: call instance void [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder::SetResult()

            -or-

            // <>t__builder.SetResult(result);
	        IL_018f: ldarg.0
	        IL_0190: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<int32> BenchmarkDotNet.Autogenerated.Runnable_0/'<WorkloadCore>d__17'::'<>t__builder'
	        IL_0195: ldloc.2
	        IL_0196: call instance void valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1<int32>::SetResult(!0)
         */
        ilBuilder.Emit(OpCodes.Ldarg_0);
        ilBuilder.Emit(OpCodes.Ldflda, builderField);
        if (returnDefaultLocal != null)
        {
            ilBuilder.EmitLdloc(returnDefaultLocal);
        }
        ilBuilder.Emit(OpCodes.Call, setResultMethod);

        // IL_0095:
        ilBuilder.MarkLabel(returnLabel);
        /*
            IL_0095: ret
         */
        ilBuilder.Emit(OpCodes.Ret);

        return asyncStateMachineTypeBuilder;
    }

    /*
        private async ValueTask __GlobalSetup()
        {
            await base.GlobalSetup();
        }
     */
    private MethodInfo EmitAsyncSingleCall(string methodName, Type asyncMethodBuilderType, MethodInfo methodToCall, bool isGlobalCleanup)
    {
        bool needsThisLocal = !methodToCall.IsStatic
            || (isGlobalCleanup && this is AsyncCoreEmitter);
        var builderInfo = BeginAsyncStateMachineTypeBuilder(methodName, asyncMethodBuilderType, needsThisLocal ? runnableBuilder : null);
        var (asyncStateMachineTypeBuilder, publicFields, (ilBuilder, _, returnLabel, stateLocal, thisLocal, _)) = builderInfo;
        var (stateField, builderField, _) = publicFields;
        EmitMoveNextImpl();
        var asyncStateMachineType = CompleteAsyncStateMachineType(asyncMethodBuilderType, builderInfo);

        return EmitAsyncCallerStub(methodName, asyncStateMachineType, publicFields);

        void EmitMoveNextImpl()
        {
            var getAwaiterMethod = methodToCall.ReturnType.GetMethod(nameof(Task.GetAwaiter), BindingFlags.Public | BindingFlags.Instance)!;
            var awaiterType = getAwaiterMethod.ReturnType;

            // .field private valuetype [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter '<>u__1'
            var awaiterField = asyncStateMachineTypeBuilder.DefineField(
                "<>u__1",
                awaiterType.IsValueType ? awaiterType : typeof(object),
                FieldAttributes.Private);

            var awaiterLocal = ilBuilder.DeclareLocal(awaiterType);
            var awaitableLocal = methodToCall.ReturnType.IsValueType
                ? ilBuilder.DeclareLocal(methodToCall.ReturnType)
                : null;

            var state0Label = ilBuilder.DefineLabel(); // IL_0046
            var completedLabel = ilBuilder.DefineLabel(); // IL_0062

            /*
                // if (num != 0)
                IL_000e: ldloc.0
                IL_000f: brfalse.s IL_0046
             */
            ilBuilder.EmitLdloc(stateLocal);
            ilBuilder.Emit(OpCodes.Brfalse_S, state0Label);

            if (isGlobalCleanup)
            {
                EmitExtraGlobalCleanup(ilBuilder, thisLocal);
            }

            /*
                // awaiter = runnable_.GlobalSetup().GetAwaiter();
                IL_0011: ldloc.1
                IL_0012: call instance class [System.Runtime]System.Threading.Tasks.Task [BenchmarkDotNet.IntegrationTests]BenchmarkDotNet.IntegrationTests.AllSetupAndCleanupTest/AllSetupAndCleanupAttributeBenchmarksTask::GlobalSetup()
                IL_0017: callvirt instance valuetype [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter [System.Runtime]System.Threading.Tasks.Task::GetAwaiter()
                IL_001c: stloc.2
             */
            if (!methodToCall.IsStatic)
            {
                ilBuilder.EmitLdloc(thisLocal!);
            }
            ilBuilder.Emit(OpCodes.Call, methodToCall);
            if (awaitableLocal is null)
            {
                ilBuilder.Emit(OpCodes.Callvirt, getAwaiterMethod);
            }
            else
            {
                ilBuilder.EmitStloc(awaitableLocal);
                ilBuilder.EmitLdloca(awaitableLocal);
                ilBuilder.Emit(OpCodes.Call, getAwaiterMethod);
            }
            ilBuilder.Emit(OpCodes.Stloc, awaiterLocal);
            /*
                // if (!awaiter.IsCompleted)
                IL_001d: ldloca.s 2
                IL_001f: call instance bool [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter::get_IsCompleted()
                IL_0024: brtrue.s IL_0062
             */
            if (awaiterType.IsValueType)
            {
                ilBuilder.EmitLdloca(awaiterLocal);
                ilBuilder.Emit(OpCodes.Call, awaiterType.GetProperty(nameof(TaskAwaiter.IsCompleted), BindingFlags.Public | BindingFlags.Instance)!.GetMethod!);
            }
            else
            {
                ilBuilder.EmitLdloc(awaiterLocal);
                ilBuilder.Emit(OpCodes.Callvirt, awaiterType.GetProperty(nameof(TaskAwaiter.IsCompleted), BindingFlags.Public | BindingFlags.Instance)!.GetMethod!);
            }
            ilBuilder.Emit(OpCodes.Brtrue_S, completedLabel);

            /*
                // num = (<>1__state = 0);
                IL_0026: ldarg.0
                IL_0027: ldc.i4.0
                IL_0028: dup
                IL_0029: stloc.0
                IL_002a: stfld int32 BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>1__state'
             */
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Ldc_I4_0);
            ilBuilder.Emit(OpCodes.Dup);
            ilBuilder.Emit(OpCodes.Stloc, stateLocal);
            ilBuilder.Emit(OpCodes.Stfld, stateField);
            /*
                // <>u__1 = awaiter;
                IL_002f: ldarg.0
                IL_0030: ldloc.2
                IL_0031: stfld valuetype [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>u__1'
             */
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.EmitLdloc(awaiterLocal);
            ilBuilder.Emit(OpCodes.Stfld, awaiterField);
            /*
                // <>t__builder.AwaitUnsafeOnCompleted(ref awaiter, ref this);
                IL_0036: ldarg.0
                IL_0037: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>t__builder'
                IL_003c: ldloca.s 2
                IL_003e: ldarg.0
                IL_003f: call instance void [System.Runtime]System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder::AwaitUnsafeOnCompleted<valuetype [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter, valuetype BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'>(!!0&, !!1&)
             */
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Ldflda, builderField);
            ilBuilder.EmitLdloca(awaiterLocal);
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Call, GetAwaitOnCompletedMethod(asyncMethodBuilderType, awaiterType, asyncStateMachineTypeBuilder));
            /*
                // return;
                IL_0044: leave.s IL_0095
             */
            ilBuilder.Emit(OpCodes.Leave_S, returnLabel);

            /*
                // awaiter = <>u__1;
                IL_0046: ldarg.0
                IL_0047: ldfld valuetype [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>u__1'
                IL_004c: stloc.2
             */
            // IL_0046:
            ilBuilder.MarkLabel(state0Label);

            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Ldfld, awaiterField);
            ilBuilder.Emit(OpCodes.Stloc, awaiterLocal);
            /*
                // <>u__1 = default(TaskAwaiter);
                IL_004d: ldarg.0
                IL_004e: ldflda valuetype [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>u__1'
                IL_0053: initobj [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter
             */
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.EmitSetFieldToDefault(awaiterField);
            /*
                // num = (<>1__state = -1);
                IL_0059: ldarg.0
                IL_005a: ldc.i4.m1
                IL_005b: dup
                IL_005c: stloc.0
                IL_005d: stfld int32 BenchmarkDotNet.Autogenerated.Runnable_0/'<__GlobalSetup>d__4'::'<>1__state'
             */
            ilBuilder.Emit(OpCodes.Ldarg_0);
            ilBuilder.Emit(OpCodes.Ldc_I4_M1);
            ilBuilder.Emit(OpCodes.Dup);
            ilBuilder.Emit(OpCodes.Stloc, stateLocal);
            ilBuilder.Emit(OpCodes.Stfld, stateField);

            /*
                // awaiter.GetResult();
                IL_0062: ldloca.s 2
                IL_0064: call instance void [System.Runtime]System.Runtime.CompilerServices.TaskAwaiter::GetResult()
                IL_0069: leave.s IL_0082
             */
            // IL_0062:
            ilBuilder.MarkLabel(completedLabel);

            var getResultMethod = awaiterType.GetMethod(nameof(TaskAwaiter.GetResult), BindingFlags.Public | BindingFlags.Instance)!;
            if (awaiterType.IsValueType)
            {
                ilBuilder.EmitLdloca(awaiterLocal);
                ilBuilder.Emit(OpCodes.Call, getResultMethod);
            }
            else
            {
                ilBuilder.EmitLdloc(awaiterLocal);
                ilBuilder.Emit(OpCodes.Callvirt, getResultMethod);
            }
            if (getResultMethod.ReturnType != typeof(void))
            {
                ilBuilder.Emit(OpCodes.Pop);
            }
        }
    }

    private static MethodInfo GetAwaitOnCompletedMethod(Type asyncMethodBuilderType, Type awaiterType, Type asyncStateMachineType)
    {
        var awaitOnCompletedMethodName = typeof(ICriticalNotifyCompletion).IsAssignableFrom(awaiterType)
            ? nameof(AsyncTaskMethodBuilder.AwaitUnsafeOnCompleted)
            : nameof(AsyncTaskMethodBuilder.AwaitOnCompleted);
        return asyncMethodBuilderType
            .GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Single(method => method.IsGenericMethod && method.Name == awaitOnCompletedMethodName)
            .MakeGenericMethod(awaiterType, asyncStateMachineType);
    }
}