using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Engines;
using BenchmarkDotNet.Extensions;
using BenchmarkDotNet.Helpers.Reflection.Emit;
using BenchmarkDotNet.Running;
using Perfolizer.Horology;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using static BenchmarkDotNet.Toolchains.InProcess.Emit.Implementation.RunnableConstants;

namespace BenchmarkDotNet.Toolchains.InProcess.Emit.Implementation;

partial class RunnableEmitter
{
    // TODO: update this to support runtime-async.
    private sealed class AsyncCoreEmitter(BuildPartition buildPartition, ModuleBuilder moduleBuilder, BenchmarkBuildInfo benchmark) : RunnableEmitter(buildPartition, moduleBuilder, benchmark)
    {
        private FieldInfo workloadContinuerAndValueTaskSourceField = null!;
        private FieldInfo clockField = null!;
        private FieldInfo invokeCountField = null!;

        protected override int GetExtraFieldsCount() => 3;

        protected override void EmitExtraFields(TypeBuilder fieldsContainerBuilder)
        {
            base.EmitExtraFields(fieldsContainerBuilder);

            workloadContinuerAndValueTaskSourceField = fieldsContainerBuilder.DefineField(
                WorkloadContinuerAndValueTaskSourceFieldName,
                typeof(WorkloadValueTaskSource),
                FieldAttributes.Public);
            clockField = fieldsContainerBuilder.DefineField(
                ClockFieldName,
                typeof(IClock),
                FieldAttributes.Public);
            invokeCountField = fieldsContainerBuilder.DefineField(
                InvokeCountFieldName,
                typeof(long),
                FieldAttributes.Public);
        }

        protected override void EmitExtraGlobalCleanup(ILGenerator ilBuilder, LocalBuilder? thisLocal)
        {
            // __fieldsContainer.workloadContinuerAndValueTaskSource?.Complete();

            var callCompleteLabel = ilBuilder.DefineLabel(); // IL_0022
            var skipCompleteLabel = ilBuilder.DefineLabel(); // IL_0027

            /*
                // WorkloadContinuerAndValueTaskSource workloadContinuerAndValueTaskSource = runnable_.__fieldsContainer.workloadContinuerAndValueTaskSource;
                IL_0011: ldloc.1
                IL_0012: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_0/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_0::__fieldsContainer
                IL_0017: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_0/FieldsContainer::workloadContinuerAndValueTaskSource
             */
            if (thisLocal != null)
            {
                ilBuilder.EmitLdloc(thisLocal);
            }
            else
            {
                ilBuilder.Emit(OpCodes.Ldarg_0);
            }
            ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
            ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
            /*
                // if (workloadContinuerAndValueTaskSource != null)
                IL_001c: dup
                IL_001d: brtrue.s IL_0022
             */
            ilBuilder.Emit(OpCodes.Dup);
            ilBuilder.Emit(OpCodes.Brtrue_S, callCompleteLabel);

            /*
                IL_001f: pop
                IL_0020: br.s IL_0027
             */
            ilBuilder.Emit(OpCodes.Pop);
            ilBuilder.Emit(OpCodes.Br, skipCompleteLabel);

            /*
                // workloadContinuerAndValueTaskSource.Complete();
                IL_0022: call instance void [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::Complete()
             */
            ilBuilder.MarkLabel(callCompleteLabel);
            ilBuilder.Emit(OpCodes.Call, typeof(WorkloadValueTaskSource).GetMethod(nameof(WorkloadValueTaskSource.Complete), BindingFlags.Public | BindingFlags.Instance)!);

            ilBuilder.MarkLabel(skipCompleteLabel);
        }

        protected override void EmitCoreImpl()
        {
            EmitOverhead();
            EmitWorkload();
        }

        private void EmitOverhead()
        {
            var noUnrollMethod = EmitNoUnrollMethod();
            EmitUnrollMethod();

            MethodInfo EmitNoUnrollMethod()
            {
                /*
                    // private ValueTask<ClockSpan> OverheadActionNoUnroll(long invokeCount, IClock clock)
                    .method private hidebysig 
	                    instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> OverheadActionNoUnroll (
		                    int64 invokeCount,
		                    class [Perfolizer]Perfolizer.Horology.IClock clock
	                    ) cil managed flags(0200)
                 */
                var invokeCountArg = new EmitParameterInfo(0, InvokeCountParamName, typeof(long));
                var methodBuilder = runnableBuilder
                    .DefineNonVirtualInstanceMethod(
                        OverheadActionNoUnrollMethodName,
                        MethodAttributes.Private,
                        EmitParameterInfo.CreateReturnParameter(typeof(ValueTask<ClockSpan>)),
                        [
                            invokeCountArg,
                            new EmitParameterInfo(1, ClockParamName, typeof(IClock))
                        ]
                    )
                    .SetAggressiveOptimizationImplementationFlag();
                invokeCountArg.SetMember(methodBuilder);

                var ilBuilder = methodBuilder.GetILGenerator();

                /*
                    .locals init (
		                [0] valuetype [Perfolizer]Perfolizer.Horology.StartedClock startedClock
	                )
                 */
                var startedClockLocal = ilBuilder.DeclareLocal(typeof(StartedClock));

                var startLoopLabel = ilBuilder.DefineLabel(); // IL_000f

                /*
                    // StartedClock startedClock = ClockExtensions.Start(clock);
	                IL_0000: ldarg.2
	                IL_0001: call valuetype [Perfolizer]Perfolizer.Horology.StartedClock [Perfolizer]Perfolizer.Horology.ClockExtensions::Start(class [Perfolizer]Perfolizer.Horology.IClock)
	                IL_0006: stloc.0
                 */
                ilBuilder.Emit(OpCodes.Ldarg_2);
                ilBuilder.Emit(OpCodes.Call, GetStartClockMethod());
                ilBuilder.EmitStloc(startedClockLocal);

                // loop
                ilBuilder.EmitLoopBeginFromArgToZero(out var loopStartLabel, out var loopHeadLabel);
                {
                    /*
	                    // __Overhead();
		                IL_0009: ldarg.0
		                IL_000a: call instance void BenchmarkDotNet.Autogenerated.Runnable_1::__Overhead()
                     */
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    EmitLoadArgFieldsForCall(ilBuilder, null);
                    ilBuilder.Emit(OpCodes.Call, overheadImplementationMethod);
                }
                ilBuilder.EmitLoopEndFromArgToZero(loopStartLabel, loopHeadLabel, invokeCountArg);

                /*
	                // return new ValueTask<ClockSpan>(startedClock.GetElapsed());
	                IL_001a: ldloca.s 0
	                IL_001c: call instance valuetype [Perfolizer]Perfolizer.Horology.ClockSpan [Perfolizer]Perfolizer.Horology.StartedClock::GetElapsed()
	                IL_0021: newobj instance void valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan>::.ctor(!0)
	                IL_0026: ret
                 */
                ilBuilder.EmitLdloca(startedClockLocal);
                ilBuilder.Emit(OpCodes.Call, typeof(StartedClock).GetMethod(nameof(StartedClock.GetElapsed), BindingFlags.Public | BindingFlags.Instance)!);
                ilBuilder.Emit(OpCodes.Newobj, typeof(ValueTask<ClockSpan>).GetConstructor([typeof(ClockSpan)])!);
                ilBuilder.Emit(OpCodes.Ret);

                return methodBuilder;
            }

            void EmitUnrollMethod()
            {
                /*
                    // private ValueTask<ClockSpan> OverheadActionUnroll(long invokeCount, IClock clock)
                    .method private hidebysig 
	                    instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> OverheadActionUnroll (
		                    int64 invokeCount,
		                    class [Perfolizer]Perfolizer.Horology.IClock clock
	                    ) cil managed flags(0200)
                 */
                var methodBuilder = runnableBuilder
                    .DefineNonVirtualInstanceMethod(
                        OverheadActionUnrollMethodName,
                        MethodAttributes.Private,
                        EmitParameterInfo.CreateReturnParameter(typeof(ValueTask<ClockSpan>)),
                        [
                            new EmitParameterInfo(0, InvokeCountParamName, typeof(long)),
                            new EmitParameterInfo(1, ClockParamName, typeof(IClock))
                        ]
                    )
                    .SetAggressiveOptimizationImplementationFlag();

                var ilBuilder = methodBuilder.GetILGenerator();

                /*
                    // return OverheadActionNoUnroll(invokeCount * 16, clock);
	                IL_0000: ldarg.0
	                IL_0001: ldarg.1
	                IL_0002: ldc.i4.s 16
	                IL_0004: conv.i8
	                IL_0005: mul
	                IL_0006: ldarg.2
	                IL_0007: call instance valuetype [System.Threading.Tasks.Extensions]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> BenchmarkDotNet.Autogenerated.Runnable_0::OverheadActionNoUnroll(int64, class [Perfolizer]Perfolizer.Horology.IClock)
	                IL_000c: ret
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldarg_1);
                ilBuilder.EmitLdc_I4(jobUnrollFactor);
                ilBuilder.Emit(OpCodes.Conv_I8);
                ilBuilder.Emit(OpCodes.Mul);
                ilBuilder.Emit(OpCodes.Ldarg_2);
                ilBuilder.Emit(OpCodes.Call, noUnrollMethod);
                ilBuilder.Emit(OpCodes.Ret);
            }
        }

        private Type GetWorkloadCoreAsyncMethodBuilderType()
        {
            // If the benchmark method overrode the caller type, use that type to get the builder type.
            if (Descriptor.WorkloadMethod.ResolveAttribute<AsyncCallerTypeAttribute>() is AsyncCallerTypeAttribute asyncCallerTypeAttribute)
            {
                return GetBuilderTypeFromUserSpecifiedAsyncType(asyncCallerTypeAttribute.AsyncCallerType);
            }
            // If the benchmark method overrode the builder, use the same builder.
            if (Descriptor.WorkloadMethod.GetAsyncMethodBuilderAttribute() is { } methodAttr
                && methodAttr.GetType().GetProperty(nameof(AsyncMethodBuilderAttribute.BuilderType), BindingFlags.Public | BindingFlags.Instance)?.GetValue(methodAttr) is Type methodBuilderType)
            {
                return methodBuilderType;
            }
            if (Descriptor.WorkloadMethod.ReturnType.GetAsyncMethodBuilderAttribute() is { } typeAttr
                && typeAttr.GetType().GetProperty(nameof(AsyncMethodBuilderAttribute.BuilderType), BindingFlags.Public | BindingFlags.Instance)?.GetValue(typeAttr) is Type typeBuilderType)
            {
                return GetConcreteBuilderType(typeBuilderType);
            }
            // Task and Task<T> are not annotated with their builder type, the C# compiler special-cases them.
            if (Descriptor.WorkloadMethod.ReturnType.IsGenericType && Descriptor.WorkloadMethod.ReturnType.GetGenericTypeDefinition() == typeof(Task<>))
            {
                return GetConcreteBuilderType(typeof(AsyncTaskMethodBuilder<>));
            }
            // Fallback to AsyncTaskMethodBuilder if the benchmark return type is Task or any awaitable type that is not a custom task-like type.
            return typeof(AsyncTaskMethodBuilder);

            Type GetBuilderTypeFromUserSpecifiedAsyncType(Type asyncType)
            {
                if (asyncType.GetAsyncMethodBuilderAttribute() is { } typeAttr
                    && typeAttr.GetType().GetProperty(nameof(AsyncMethodBuilderAttribute.BuilderType), BindingFlags.Public | BindingFlags.Instance)?.GetValue(typeAttr) is Type typeBuilderType)
                {
                    return GetConcreteBuilderType(typeBuilderType);
                }
                // Task and Task<T> are not annotated with their builder type, the C# compiler special-cases them.
                if (asyncType == typeof(Task))
                {
                    return typeof(AsyncTaskMethodBuilder);
                }
                if (asyncType.IsGenericType && asyncType.GetGenericTypeDefinition() == typeof(Task<>))
                {
                    return typeof(AsyncTaskMethodBuilder<>).MakeGenericType([asyncType.GetGenericArguments()[0]]);
                }
                throw new NotSupportedException($"AsyncMethodBuilderAttribute not found on type {asyncType.GetDisplayName()} from {Descriptor.DisplayInfo}");
            }

            Type GetConcreteBuilderType(Type builderType)
            {
                if (!builderType.IsGenericTypeDefinition)
                {
                    return builderType;
                }
                if (builderType.GetGenericArguments().Length != 1)
                {
                    throw new NotSupportedException($"AsyncMethodBuilder {builderType.GetDisplayName()} has generic arity greater than 1.");
                }
                var resultType = Descriptor.WorkloadMethod.ReturnType
                    .GetMethod(nameof(Task.GetAwaiter), BindingFlags.Public | BindingFlags.Instance)!
                    .ReturnType
                    .GetMethod(nameof(TaskAwaiter.GetResult), BindingFlags.Public | BindingFlags.Instance)!
                    .ReturnType;
                return builderType.MakeGenericType([resultType]);
            }
        }

        private void EmitWorkload()
        {
            var asyncMethodBuilderType = GetWorkloadCoreAsyncMethodBuilderType();
            var builderInfo = BeginAsyncStateMachineTypeBuilder(WorkloadCoreMethodName, asyncMethodBuilderType, runnableBuilder);
            var (asyncStateMachineTypeBuilder, publicFields, (ilBuilder, endTryLabel, returnLabel, stateLocal, thisLocal, returnDefaultLocal)) = builderInfo;
            var (stateField, builderField, _) = publicFields;
            var startedClockField = asyncStateMachineTypeBuilder.DefineField(
                "<startedClock>5__2",
                typeof(StartedClock),
                FieldAttributes.Private
            );
            var workloadContinuerAwaiterField = asyncStateMachineTypeBuilder.DefineField(
                "<>u__1",
                typeof(ValueTaskAwaiter<bool>),
                FieldAttributes.Private
            );
            var benchmarkAwaiterField = asyncStateMachineTypeBuilder.DefineField(
                "<>u__2",
                Descriptor.WorkloadMethod.ReturnType
                    .GetMethod(nameof(Task.GetAwaiter), BindingFlags.Public | BindingFlags.Instance)!
                    .ReturnType,
                FieldAttributes.Private
            );
            EmitMoveNextImpl();
            var asyncStateMachineType = CompleteAsyncStateMachineType(asyncMethodBuilderType, builderInfo);

            var workloadCoreMethod = EmitAsyncCallerStub(WorkloadCoreMethodName, asyncStateMachineType, publicFields);

            var startWorkloadMethod = EmitAsyncSingleCall(StartWorkloadMethodName, typeof(AsyncVoidMethodBuilder), workloadCoreMethod, false);

            var noUnrollMethod = EmitNoUnrollMethod();
            EmitUnrollMethod();

            void EmitMoveNextImpl()
            {
                var isCompleteAwaitableLocal = ilBuilder.DeclareLocal(typeof(ValueTask<bool>));
                var isCompleteAwaiterLocal = ilBuilder.DeclareLocal(typeof(ValueTaskAwaiter<bool>));
                var benchmarkAwaitableLocal = Descriptor.WorkloadMethod.ReturnType.IsValueType
                    ? ilBuilder.DeclareLocal(Descriptor.WorkloadMethod.ReturnType)
                    : null;
                var benchmarkAwaiterLocal = ilBuilder.DeclareLocal(benchmarkAwaiterField.FieldType);
                var invokeCountLocal = ilBuilder.DeclareLocal(typeof(long));
                var exceptionLocal = ilBuilder.DeclareLocal(typeof(Exception));

                var getIsCompleteContinuationLabel = ilBuilder.DefineLabel();
                var getIsCompleteGetResultLabel = ilBuilder.DefineLabel();
                var startClockLabel = ilBuilder.DefineLabel();
                var callBenchmarkLabel = ilBuilder.DefineLabel();
                var callBenchmarkLoopLabel = ilBuilder.DefineLabel();
                var benchmarkContinuationLabel = ilBuilder.DefineLabel();
                var benchmarkContinuationGetResultLabel = ilBuilder.DefineLabel();
                var setResultContinuationLabel = ilBuilder.DefineLabel();
                var setResultGetResultLabel = ilBuilder.DefineLabel();

                // Roslyn preamble.
                ilBuilder.EmitLdloc(stateLocal);
                ilBuilder.Emit(OpCodes.Ldc_I4_2);
                ilBuilder.Emit(OpCodes.Pop);
                ilBuilder.Emit(OpCodes.Pop);
                ilBuilder.Emit(OpCodes.Nop);

                ilBuilder.BeginExceptionBlock();
                {
                    // State dispatch: 0 → getIsComplete resume, 1 → benchmark resume, 2 → setResult resume
                    ilBuilder.EmitLdloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Brfalse, getIsCompleteContinuationLabel);

                    ilBuilder.EmitLdloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Ldc_I4_1);
                    ilBuilder.Emit(OpCodes.Beq, benchmarkContinuationLabel);

                    ilBuilder.EmitLdloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Ldc_I4_2);
                    ilBuilder.Emit(OpCodes.Beq, setResultContinuationLabel);

                    // ===== await workloadValueTaskSource.GetIsComplete() =====
                    // var awaitable = workloadValueTaskSource.GetIsComplete();
                    ilBuilder.EmitLdloc(thisLocal!);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                    ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadValueTaskSource).GetMethod(nameof(WorkloadValueTaskSource.GetIsComplete), BindingFlags.Public | BindingFlags.Instance)!);
                    ilBuilder.EmitStloc(isCompleteAwaitableLocal);
                    // var awaiter = awaitable.GetAwaiter();
                    ilBuilder.EmitLdloca(isCompleteAwaitableLocal);
                    ilBuilder.Emit(OpCodes.Call, typeof(ValueTask<bool>).GetMethod(nameof(ValueTask<bool>.GetAwaiter), BindingFlags.Public | BindingFlags.Instance)!);
                    ilBuilder.EmitStloc(isCompleteAwaiterLocal);
                    // if (awaiter.IsCompleted) goto getIsCompleteGetResultLabel;
                    ilBuilder.EmitLdloca(isCompleteAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Call, typeof(ValueTaskAwaiter<bool>).GetProperty(nameof(ValueTaskAwaiter<bool>.IsCompleted), BindingFlags.Public | BindingFlags.Instance)!.GetMethod!);
                    ilBuilder.Emit(OpCodes.Brtrue, getIsCompleteGetResultLabel);
                    // state = 0; <>u__1 = awaiter;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_0);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitLdloc(isCompleteAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Stfld, workloadContinuerAwaiterField);
                    // <>t__builder.AwaitUnsafeOnCompleted(ref awaiter, ref this);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldflda, builderField);
                    ilBuilder.EmitLdloca(isCompleteAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Call, GetAwaitOnCompletedMethod(asyncMethodBuilderType, typeof(ValueTaskAwaiter<bool>), asyncStateMachineTypeBuilder));
                    // return;
                    ilBuilder.Emit(OpCodes.Leave, returnLabel);

                    // --- Resume from state 0 ---
                    ilBuilder.MarkLabel(getIsCompleteContinuationLabel);
                    // awaiter = <>u__1;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAwaiterField);
                    ilBuilder.EmitStloc(isCompleteAwaiterLocal);
                    // <>u__1 = default;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitSetFieldToDefault(workloadContinuerAwaiterField);
                    // state = -1;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_M1);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);

                    // --- GetResult ---
                    ilBuilder.MarkLabel(getIsCompleteGetResultLabel);
                    // bool isComplete = awaiter.GetResult();
                    ilBuilder.EmitLdloca(isCompleteAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Call, typeof(ValueTaskAwaiter<bool>).GetMethod(nameof(ValueTaskAwaiter<bool>.GetResult), BindingFlags.Public | BindingFlags.Instance)!);
                    // if (!isComplete) goto startClockLabel;
                    ilBuilder.Emit(OpCodes.Brfalse, startClockLabel);
                    // return default;
                    ilBuilder.MaybeEmitSetLocalToDefault(returnDefaultLocal);
                    ilBuilder.Emit(OpCodes.Leave, endTryLabel);

                    // ===== while(true) { startClock → benchmark loop → SetResultAndGetIsComplete } =====

                    // startedClock = ClockExtensions.Start(clock);
                    ilBuilder.MarkLabel(startClockLabel);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitLdloc(thisLocal!);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldfld, clockField);
                    ilBuilder.Emit(OpCodes.Call, GetStartClockMethod());
                    ilBuilder.Emit(OpCodes.Stfld, startedClockField);
                    // goto callBenchmarkLoopLabel;
                    ilBuilder.Emit(OpCodes.Br, callBenchmarkLoopLabel);

                    // --- Benchmark call ---
                    ilBuilder.MarkLabel(callBenchmarkLabel);
                    if (!Descriptor.WorkloadMethod.IsStatic)
                    {
                        ilBuilder.EmitLdloc(thisLocal!);
                    }
                    EmitLoadArgFieldsForCall(ilBuilder, thisLocal);
                    ilBuilder.Emit(OpCodes.Call, Descriptor.WorkloadMethod);
                    if (benchmarkAwaitableLocal == null)
                    {
                        ilBuilder.Emit(OpCodes.Callvirt, Descriptor.WorkloadMethod.ReturnType.GetMethod(nameof(Task.GetAwaiter), BindingFlags.Public | BindingFlags.Instance)!);
                    }
                    else
                    {
                        ilBuilder.EmitStloc(benchmarkAwaitableLocal);
                        ilBuilder.EmitLdloca(benchmarkAwaitableLocal);
                        ilBuilder.Emit(OpCodes.Call, Descriptor.WorkloadMethod.ReturnType.GetMethod(nameof(Task.GetAwaiter), BindingFlags.Public | BindingFlags.Instance)!);
                    }
                    // if (awaiter.IsCompleted) goto benchmarkContinuationGetResultLabel;
                    ilBuilder.EmitStloc(benchmarkAwaiterLocal);
                    ilBuilder.EmitLdloca(benchmarkAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Call, benchmarkAwaiterField.FieldType.GetProperty(nameof(TaskAwaiter.IsCompleted), BindingFlags.Public | BindingFlags.Instance)!.GetMethod!);
                    ilBuilder.Emit(OpCodes.Brtrue, benchmarkContinuationGetResultLabel);
                    // state = 1; <>u__2 = awaiter;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_1);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitLdloc(benchmarkAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Stfld, benchmarkAwaiterField);
                    // <>t__builder.AwaitUnsafeOnCompleted(ref awaiter, ref this);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldflda, builderField);
                    ilBuilder.EmitLdloca(benchmarkAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Call, GetAwaitOnCompletedMethod(asyncMethodBuilderType, benchmarkAwaiterField.FieldType, asyncStateMachineTypeBuilder));
                    // return;
                    ilBuilder.Emit(OpCodes.Leave, returnLabel);

                    // --- Resume from state 1 ---
                    ilBuilder.MarkLabel(benchmarkContinuationLabel);
                    // awaiter = <>u__2;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldfld, benchmarkAwaiterField);
                    ilBuilder.EmitStloc(benchmarkAwaiterLocal);
                    // <>u__2 = default;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitSetFieldToDefault(benchmarkAwaiterField);
                    // state = -1;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_M1);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);

                    // --- Benchmark GetResult ---
                    ilBuilder.MarkLabel(benchmarkContinuationGetResultLabel);
                    ilBuilder.EmitLdloca(benchmarkAwaiterLocal);
                    var benchmarkAwaiterGetResultMethod = benchmarkAwaiterField.FieldType.GetMethod(nameof(TaskAwaiter.GetResult), BindingFlags.Public | BindingFlags.Instance)!;
                    ilBuilder.Emit(OpCodes.Call, benchmarkAwaiterGetResultMethod);
                    if (benchmarkAwaiterGetResultMethod.ReturnType != typeof(void))
                    {
                        ilBuilder.Emit(OpCodes.Pop);
                    }

                    // --- Benchmark loop: if (--invokeCount >= 0) goto callBenchmarkLabel ---
                    ilBuilder.MarkLabel(callBenchmarkLoopLabel);
                    ilBuilder.EmitLdloc(thisLocal!);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldflda, invokeCountField);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.Emit(OpCodes.Ldind_I8);
                    ilBuilder.Emit(OpCodes.Ldc_I4_1);
                    ilBuilder.Emit(OpCodes.Conv_I8);
                    ilBuilder.Emit(OpCodes.Sub);
                    ilBuilder.EmitStloc(invokeCountLocal);
                    ilBuilder.EmitLdloc(invokeCountLocal);
                    ilBuilder.Emit(OpCodes.Stind_I8);
                    ilBuilder.EmitLdloc(invokeCountLocal);
                    ilBuilder.Emit(OpCodes.Ldc_I4_0);
                    ilBuilder.Emit(OpCodes.Conv_I8);
                    ilBuilder.Emit(OpCodes.Bge, callBenchmarkLabel);

                    // ===== await workloadValueTaskSource.SetResultAndGetIsComplete(startedClock.GetElapsed()) =====
                    // var awaitable = workloadValueTaskSource.SetResultAndGetIsComplete(startedClock.GetElapsed());
                    ilBuilder.EmitLdloc(thisLocal!);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldflda, startedClockField);
                    ilBuilder.Emit(OpCodes.Call, typeof(StartedClock).GetMethod(nameof(StartedClock.GetElapsed), BindingFlags.Public | BindingFlags.Instance)!);
                    ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadValueTaskSource).GetMethod(nameof(WorkloadValueTaskSource.SetResultAndGetIsComplete), BindingFlags.Public | BindingFlags.Instance)!);
                    ilBuilder.EmitStloc(isCompleteAwaitableLocal);
                    // startedClock = default;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitSetFieldToDefault(startedClockField);
                    // var awaiter = awaitable.GetAwaiter();
                    ilBuilder.EmitLdloca(isCompleteAwaitableLocal);
                    ilBuilder.Emit(OpCodes.Call, typeof(ValueTask<bool>).GetMethod(nameof(ValueTask<bool>.GetAwaiter), BindingFlags.Public | BindingFlags.Instance)!);
                    ilBuilder.EmitStloc(isCompleteAwaiterLocal);
                    // if (awaiter.IsCompleted) goto setResultGetResultLabel;
                    ilBuilder.EmitLdloca(isCompleteAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Call, typeof(ValueTaskAwaiter<bool>).GetProperty(nameof(ValueTaskAwaiter<bool>.IsCompleted), BindingFlags.Public | BindingFlags.Instance)!.GetMethod!);
                    ilBuilder.Emit(OpCodes.Brtrue, setResultGetResultLabel);
                    // state = 2; <>u__1 = awaiter;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_2);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitLdloc(isCompleteAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Stfld, workloadContinuerAwaiterField);
                    // <>t__builder.AwaitUnsafeOnCompleted(ref awaiter, ref this);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldflda, builderField);
                    ilBuilder.EmitLdloca(isCompleteAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Call, GetAwaitOnCompletedMethod(asyncMethodBuilderType, typeof(ValueTaskAwaiter<bool>), asyncStateMachineTypeBuilder));
                    // return;
                    ilBuilder.Emit(OpCodes.Leave, returnLabel);

                    // --- Resume from state 2 ---
                    ilBuilder.MarkLabel(setResultContinuationLabel);
                    // awaiter = <>u__1;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAwaiterField);
                    ilBuilder.EmitStloc(isCompleteAwaiterLocal);
                    // <>u__1 = default;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.EmitSetFieldToDefault(workloadContinuerAwaiterField);
                    // state = -1;
                    ilBuilder.Emit(OpCodes.Ldarg_0);
                    ilBuilder.Emit(OpCodes.Ldc_I4_M1);
                    ilBuilder.Emit(OpCodes.Dup);
                    ilBuilder.EmitStloc(stateLocal);
                    ilBuilder.Emit(OpCodes.Stfld, stateField);

                    // --- SetResult GetResult ---
                    ilBuilder.MarkLabel(setResultGetResultLabel);
                    // bool isComplete = awaiter.GetResult();
                    ilBuilder.EmitLdloca(isCompleteAwaiterLocal);
                    ilBuilder.Emit(OpCodes.Call, typeof(ValueTaskAwaiter<bool>).GetMethod(nameof(ValueTaskAwaiter<bool>.GetResult), BindingFlags.Public | BindingFlags.Instance)!);
                    // if (!isComplete) goto startClockLabel;
                    ilBuilder.Emit(OpCodes.Brfalse, startClockLabel);
                    // return default;
                    ilBuilder.MaybeEmitSetLocalToDefault(returnDefaultLocal);
                    ilBuilder.Emit(OpCodes.Leave, endTryLabel);
                }
                // end .try
                ilBuilder.BeginCatchBlock(typeof(Exception));
                {
                    // catch (Exception exception)
                    ilBuilder.EmitStloc(exceptionLocal);
                    // workloadValueTaskSource.SetException(exception);
                    ilBuilder.EmitLdloc(thisLocal!);
                    ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                    ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                    ilBuilder.EmitLdloc(exceptionLocal);
                    ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadValueTaskSource).GetMethod(nameof(WorkloadValueTaskSource.SetException), [typeof(Exception)])!);
                    // result = default;
                    ilBuilder.MaybeEmitSetLocalToDefault(returnDefaultLocal);

                    ilBuilder.EndExceptionBlock();
                } // end handler
            }

            MethodInfo EmitNoUnrollMethod()
            {
                /*
                    // private ValueTask<ClockSpan> WorkloadActionNoUnroll(long invokeCount, IClock clock)
                    .method private hidebysig 
	                    instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> WorkloadActionNoUnroll (
		                    int64 invokeCount,
		                    class [Perfolizer]Perfolizer.Horology.IClock clock
	                    ) cil managed flags(0200)
                 */
                var methodBuilder = runnableBuilder
                    .DefineNonVirtualInstanceMethod(
                        WorkloadActionNoUnrollMethodName,
                        MethodAttributes.Private,
                        EmitParameterInfo.CreateReturnParameter(typeof(ValueTask<ClockSpan>)),
                        [
                            new EmitParameterInfo(0, InvokeCountParamName, typeof(long)),
                            new EmitParameterInfo(1, ClockParamName, typeof(IClock))
                        ]
                    )
                    .SetAggressiveOptimizationImplementationFlag();

                var ilBuilder = methodBuilder.GetILGenerator();

                var callContinueLabel = ilBuilder.DefineLabel(); // IL_003b

                /*
                    // __fieldsContainer.invokeCount = invokeCount;
	                IL_0000: ldarg.0
	                IL_0001: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_0006: ldarg.1
	                IL_0007: stfld int64 BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::invokeCount
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Ldarg_1);
                ilBuilder.Emit(OpCodes.Stfld, invokeCountField);
                /*
	                // __fieldsContainer.clock = clock;
	                IL_000c: ldarg.0
	                IL_000d: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_0012: ldarg.2
	                IL_0013: stfld class [Perfolizer]Perfolizer.Horology.IClock BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::clock
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Ldarg_2);
                ilBuilder.Emit(OpCodes.Stfld, clockField);
                /*
	                // if (__fieldsContainer.workloadContinuerAndValueTaskSource == null)
	                IL_0018: ldarg.0
	                IL_0019: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_001e: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
	                IL_0023: brtrue.s IL_003b
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                ilBuilder.Emit(OpCodes.Brtrue_S, callContinueLabel);

                /*
	                // __fieldsContainer.workloadContinuerAndValueTaskSource = new WorkloadContinuerAndValueTaskSource();
	                IL_0025: ldarg.0
	                IL_0026: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_002b: newobj instance void [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::.ctor()
	                IL_0030: stfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Newobj, typeof(WorkloadValueTaskSource).GetConstructor([])!);
                ilBuilder.Emit(OpCodes.Stfld, workloadContinuerAndValueTaskSourceField);
                /*
	                // __StartWorkload();
	                IL_0035: ldarg.0
	                IL_0036: call instance void BenchmarkDotNet.Autogenerated.Runnable_1::__StartWorkload()
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Call, startWorkloadMethod);

                /*
	                // return __fieldsContainer.workloadContinuerAndValueTaskSource.Continue();
	                IL_003b: ldarg.0
	                IL_003c: ldflda valuetype BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer BenchmarkDotNet.Autogenerated.Runnable_1::__fieldsContainer
	                IL_0041: ldfld class [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource BenchmarkDotNet.Autogenerated.Runnable_1/FieldsContainer::workloadContinuerAndValueTaskSource
	                IL_0046: callvirt instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> [BenchmarkDotNet]BenchmarkDotNet.Engines.WorkloadContinuerAndValueTaskSource::Continue()
	                IL_004b: ret
                 */
                ilBuilder.MarkLabel(callContinueLabel);
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldflda, fieldsContainerField);
                ilBuilder.Emit(OpCodes.Ldfld, workloadContinuerAndValueTaskSourceField);
                ilBuilder.Emit(OpCodes.Callvirt, typeof(WorkloadValueTaskSource).GetMethod(nameof(WorkloadValueTaskSource.Continue), BindingFlags.Public | BindingFlags.Instance)!);
                ilBuilder.Emit(OpCodes.Ret);

                return methodBuilder;
            }

            void EmitUnrollMethod()
            {
                /*
                    // private ValueTask<ClockSpan> WorkloadActionUnroll(long invokeCount, IClock clock)
                    .method private hidebysig 
	                    instance valuetype [System.Runtime]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> WorkloadActionUnroll (
		                    int64 invokeCount,
		                    class [Perfolizer]Perfolizer.Horology.IClock clock
	                    ) cil managed flags(0200)
                 */
                var methodBuilder = runnableBuilder
                    .DefineNonVirtualInstanceMethod(
                        WorkloadActionUnrollMethodName,
                        MethodAttributes.Private,
                        EmitParameterInfo.CreateReturnParameter(typeof(ValueTask<ClockSpan>)),
                        [
                            new EmitParameterInfo(0, InvokeCountParamName, typeof(long)),
                            new EmitParameterInfo(1, ClockParamName, typeof(IClock))
                        ]
                    )
                    .SetAggressiveOptimizationImplementationFlag();

                var ilBuilder = methodBuilder.GetILGenerator();

                /*
                    // return WorkloadActionNoUnroll(invokeCount * 16, clock);
	                IL_0000: ldarg.0
	                IL_0001: ldarg.1
	                IL_0002: ldc.i4.s 16
	                IL_0004: conv.i8
	                IL_0005: mul
	                IL_0006: ldarg.2
	                IL_0007: call instance valuetype [System.Threading.Tasks.Extensions]System.Threading.Tasks.ValueTask`1<valuetype [Perfolizer]Perfolizer.Horology.ClockSpan> BenchmarkDotNet.Autogenerated.Runnable_0::WorkloadActionNoUnroll(int64, class [Perfolizer]Perfolizer.Horology.IClock)
	                IL_000c: ret
                 */
                ilBuilder.Emit(OpCodes.Ldarg_0);
                ilBuilder.Emit(OpCodes.Ldarg_1);
                ilBuilder.EmitLdc_I4(jobUnrollFactor);
                ilBuilder.Emit(OpCodes.Conv_I8);
                ilBuilder.Emit(OpCodes.Mul);
                ilBuilder.Emit(OpCodes.Ldarg_2);
                ilBuilder.Emit(OpCodes.Call, noUnrollMethod);
                ilBuilder.Emit(OpCodes.Ret);
            }
        }
    }
}