name: Documentation Checks

on:
  push:
    branches:
      - master
    paths:
      - "docs/**/*"
  pull_request:
    branches:
      - master
    paths:
      - "docs/**/*"
jobs:
  spellcheck:
    name: "Docs: Spellcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: "16"
      - run: npm install -g cspell
        name: Install cSpell
      - run: cspell --config ./cSpell.json "docs/**/*.md" --no-progress
        name: Run cSpell
